"""IntentPacket — the structured output of the Socratic interview.

This is the input to the deterministic compiler (compiler.py).
An IntentPacket captures the semantic decisions a researcher makes during
the Phase 0 interview and provides enough information for the compiler to
produce a byte-identical ``protocol.json`` without any LLM or network calls.

Design contract
---------------
- The intent packet is the **minimal** specification from which a full
  ``ResearchProtocol`` can be reconstructed deterministically.
- Fields not present in the intent packet are filled by the playbook preset
  (see ``presets.py``).
- IDs for research questions (``RQ1``, ``RQ2``, …) and screening criteria
  (``INC-01``, ``EXC-01``, …) are generated by the compiler from the
  declaration order.  The intent packet author refers to them by their
  *expected generated labels* when filling in ``maps_to_rqs``.
- ``genesis_timestamp`` is a required pinned ISO-8601 timestamp that becomes
  the ``created_at`` field in the protocol.  Requiring an explicit value
  closes the non-determinism gap identified in the Cycle A review
  (Reviewer 1 gap #4 / Reviewer 2 observation on ``created_at``).

Nondeterminism boundary (restated for Cycle B)
-----------------------------------------------
    IntentPacket (structured, authored or LLM-emitted)
        → compile_protocol()   [pure function, zero LLM, zero network]
        → ResearchProtocol     [canonical bytes, sha256 fingerprint]

The intent packet itself may be emitted by the Socratic interview agent
(nondeterministic LLM conversation) — but once captured, it is a
fixed, deterministic input to the compiler.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from scholar_protocol.models import DimensionDataType, EpistemologicalParadigm, PlaybookType


# ---------------------------------------------------------------------------
# Sub-models for the intent packet
# ---------------------------------------------------------------------------


class RQIntent(BaseModel):
    """A single research question as expressed in the intent packet.

    The compiler generates the RQ ``id`` (``RQ1``, ``RQ2``, …) from the
    declaration order.  Authors reference these generated labels in criterion
    ``maps_to_rqs`` lists.
    """

    model_config = ConfigDict(populate_by_name=True)

    text: str = Field(..., description="Formal research question text")
    target_facet: str = Field(
        ..., description="The conceptual facet addressed, e.g. 'evaluation_metrics'"
    )
    synthesis_type: str = Field(
        "Comparative Matrix",
        description="How findings will be synthesised, e.g. 'Comparative Matrix', 'Narrative'",
    )
    required_evidence_type: str = Field(
        ..., description="Evidence class required to answer this RQ"
    )


class ConceptClusterIntent(BaseModel):
    """A keyword cluster as expressed in the intent packet."""

    model_config = ConfigDict(populate_by_name=True)

    concept: str = Field(..., description="Primary conceptual term")
    synonyms: List[str] = Field(default_factory=list)
    boolean_operator: str = Field("OR")


class CriterionIntent(BaseModel):
    """A single inclusion or exclusion criterion as expressed in the intent packet.

    The compiler generates the criterion ``id`` (``INC-01``, ``EXC-01``, …)
    from the declaration order within the inclusion and exclusion lists.
    ``maps_to_rqs`` should use the generated RQ labels (``RQ1``, ``RQ2``, …).
    """

    model_config = ConfigDict(populate_by_name=True)

    criterion: str = Field(..., description="Explicit condition description")
    maps_to_rqs: List[str] = Field(
        default_factory=list,
        description="Generated RQ labels this criterion serves, e.g. ['RQ1', 'RQ2']",
    )
    reason_category: Optional[str] = Field(
        None,
        description="Optional rejection category e.g. 'WRONG_POPULATION', 'NO_EVALUATION'",
    )


class MatrixDimensionIntent(BaseModel):
    """A custom extraction dimension as expressed in the intent packet.

    Unlike RQ and criterion IDs, dimension IDs are **author-provided** in the
    intent packet (they are semantic slugs used as column keys by the RAG
    extractor, so they must be meaningful, not sequential).
    """

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(..., description="Unique semantic slug, e.g. 'sample_size'")
    name: str = Field(..., description="Human-readable column header")
    description: str = Field(..., description="Extraction guidance for the RAG extractor")
    target_section_category: Optional[str] = Field(None)
    data_type: DimensionDataType = Field(DimensionDataType.FREE_TEXT)
    required: bool = Field(False)
    fallback_value: str = Field("Not Reported")


# ---------------------------------------------------------------------------
# Root intent packet
# ---------------------------------------------------------------------------


class IntentPacket(BaseModel):
    """Structured, frozen intent produced by the Socratic interview.

    This is the deterministic input to ``compile_protocol()``.  Every field
    that is ``None`` (or absent) is resolved from the playbook preset.
    """

    model_config = ConfigDict(populate_by_name=True)

    # ---- Identity (always required) ----------------------------------------

    protocol_id: str = Field(
        ..., description="Unique protocol identifier, e.g. 'proto-20260901-ai-dev'"
    )
    genesis_timestamp: str = Field(
        ...,
        description=(
            "Pinned ISO-8601 UTC timestamp that becomes ``created_at`` in the protocol. "
            "Must be explicit to guarantee sha256 reproducibility across runs."
        ),
    )
    project_slug: str = Field(
        ..., description="Workspace slug, e.g. 'ai-developer-productivity'"
    )
    playbook_type: PlaybookType = Field(
        ..., description="Canonical research archetype; selects the default preset"
    )

    # ---- Metadata -----------------------------------------------------------

    title: str = Field("", description="Human-readable project title")
    lead_researcher: str = Field("", description="Primary researcher name")
    target_venue_type: str = Field("", description="Target publication venue")
    timeline_weeks: Optional[int] = Field(
        None,
        description="Project timeline in weeks; None = use playbook preset default",
    )

    # ---- Epistemology -------------------------------------------------------

    primary_paradigm: Optional[EpistemologicalParadigm] = Field(
        None,
        description="Epistemological stance; None = use playbook preset default",
    )
    secondary_paradigm: Optional[EpistemologicalParadigm] = Field(None)
    unit_of_analysis: str = Field(
        ..., description="The concrete entity being studied"
    )
    trustworthiness_framework: Optional[str] = Field(
        None,
        description="Quality/rigor framework; None = use playbook preset default",
    )
    epistemological_rationale: str = Field(
        ..., description="Narrative justification for the paradigm choice"
    )
    incompatible_concepts: List[str] = Field(default_factory=list)

    # ---- Research questions (required, min 1) -------------------------------

    research_questions: List[RQIntent] = Field(
        ...,
        min_length=1,
        description="At least one research question required",
    )

    # ---- Search strategy ----------------------------------------------------

    core_concepts: List[ConceptClusterIntent] = Field(
        ...,
        min_length=1,
        description="At least one concept cluster required",
    )
    target_databases: Optional[List[str]] = Field(
        None,
        description="Target databases; None = use playbook preset default",
    )
    start_year: Optional[int] = Field(None)
    end_year: Optional[int] = Field(None)
    languages: Optional[List[str]] = Field(
        None,
        description="ISO 639-1 language codes; None = use playbook preset default",
    )
    open_access_preferred: Optional[bool] = Field(None)
    pool_min: Optional[int] = Field(
        None,
        description="Minimum candidate pool size; None = use playbook preset default",
    )
    pool_max: Optional[int] = Field(
        None,
        description="Maximum candidate pool size; None = use playbook preset default",
    )

    # ---- Screening criteria (required, min 1 each) --------------------------

    inclusion_criteria: List[CriterionIntent] = Field(
        ...,
        min_length=1,
        description="At least one inclusion criterion required",
    )
    exclusion_criteria: List[CriterionIntent] = Field(
        ...,
        min_length=1,
        description="At least one exclusion criterion required",
    )
    two_tier_screening: Optional[bool] = Field(
        None,
        description="Two-tier screening flag; None = use playbook preset default",
    )

    # ---- Extraction dimensions (optional) -----------------------------------

    matrix_dimensions: List[MatrixDimensionIntent] = Field(default_factory=list)

    # ---- Verification overrides (all None = use preset defaults) ------------

    retraction_check_required: Optional[bool] = Field(None)
    coi_and_funding_audit_required: Optional[bool] = Field(None)
    reproducibility_das_cas_check: Optional[bool] = Field(None)
    minimum_trust_score_threshold: Optional[float] = Field(
        None, ge=0.0, le=10.0
    )
